apiVersion: v1
data:
  db: U0VDQUNudGtSM3ByY3Q2ajJoRHRNbGxDN1hvelhndndaWGRLR2VOWUVsdW52aFhRb3BnZWZEZHdLYnhhN29idk1HRFBHU0lZaXJTcnFxSERkSmxvdWc9PQo=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
type: Opaque
