apiVersion: v1
data:
  flask: T2Z3T0FMZ2wveFBTSjFGbEZmSkdvU0VvVEljVTJ4TnhTQm41N29SeWpBNGdCMWIyK0hBTzNGK2tGQUt4K0lSVmNadXJqREVlaUdkYW1GMUFnTUdWTXc9PQo=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flask
  name: flask
type: Opaque
