apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/db_network: "true"
        io.kompose.network/nginx_network: "true"
        io.kompose.service: web
    spec:
      containers:
      - image: drvanon/gridt
        env:
          - name: FLASK_CONFIGURATION
            value: /etc/gridt/gridt.conf
        imagePullPolicy: IfNotPresent
        name: web
        resources: {}
        volumeMounts:
        - mountPath: /run/secrets/flask
          name: flask
        - mountPath: /etc/gridt
          name: web-conf
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: web-conf
        configMap:
          name: web-conf-mmtg6fdcc9
      - name: flask
        secret:
          secretName: flask-7572dmdm7b
status: {}
